version: '3.7'
services:
    nodered:
        container_name: nodered
        image: dpflores/acme_nodered:base
        environment:
            TZ: America/Lima
        # volumes:
            # - "./nodered-data:/data"
        privileged: true
        restart: "always"
        network_mode: "host"
         
            
    db:
        image: linuxserver/mariadb:10.6.13
        container_name: mariadb
        volumes:
        - ./mariadb-data:/config
        privileged: true
        restart: always
        ports:
        - 3306:3306
        environment:
            PUID: 1000
            PGID: 1000
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: acme_db
            TZ: America/Lima
            
            # MYSQL_USER: acme
            # MYSQL_PASSWORD: /run/secrets/db_password
            # MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
            # FILE__PASSWORD: /run/secrets/db_password
    
        secrets:
            - db_password
            - db_root_password
        # networks:
        #     - connect_network    

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
